#ifndef ARDUINO_SECRETS_H_
#define ARDUINO_SECRETS_H_

#define SECRET_WIFI_SSID ""
#define SECRET_WIFI_PASSWORD ""
#define SECRET_ADAFRUIT_IO_USERNAME ""
#define SECRET_ADAFRUIT_IO_KEY ""

#endif  // ARDUINO_SECRETS_H_
